# Generated by Django 4.1 on 2022-10-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0002_alter_perfil_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('Comprar', 'Comprar'), ('Vender', 'Vender')], max_length=7)),
            ],
            options={
                'verbose_name': 'historico',
                'verbose_name_plural': 'historicos',
            },
        ),
    ]
