# Generated by Django 4.1 on 2022-10-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0003_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='historico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='Perfil_app.historico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='acao',
            field=models.CharField(blank=True, choices=[('Comprar', 'Comprar'), ('Vender', 'Vender')], max_length=7, null=True),
        ),
    ]
