# Generated by Django 4.1 on 2022-10-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0004_perfil_historico_alter_historico_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='acao',
            field=models.CharField(choices=[('Comprar', 'Comprar'), ('Vender', 'Vender')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='historico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='Perfil_app.historico'),
        ),
    ]
