# Generated by Django 4.1 on 2022-10-06 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Perfil_app', '0005_alter_historico_acao_alter_perfil_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='historico',
        ),
        migrations.AddField(
            model_name='historico',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
