# Generated by Django 4.1 on 2022-10-06 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0006_remove_perfil_historico_historico_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='Perfil_app.perfil'),
        ),
    ]
