# Generated by Django 4.1 on 2022-10-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0007_alter_historico_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='usuario',
            new_name='perfil',
        ),
    ]
