# Generated by Django 4.1 on 2022-10-06 01:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos_app', '0002_alter_produto_foto'),
        ('Perfil_app', '0008_rename_usuario_historico_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='historico',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historico',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='Produtos_app.produto'),
        ),
    ]
