# Generated by Django 4.1 on 2022-10-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0009_rename_nome_completo_perfil_nome_historico_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
