# Generated by Django 4.1 on 2022-10-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
