# Generated by Django 4.1 on 2022-10-11 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos_app', '0002_alter_produto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'imagens',
                'verbose_name_plural': 'imagenss',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='fotos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produtos_app.imagens'),
        ),
    ]
