# Generated by Django 4.1 on 2022-10-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos_app', '0005_alter_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='titulo',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos_app.categoria'),
        ),
    ]
