# Generated by Django 4.1.2 on 2022-10-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos_app', '0006_rename_titulo_categoria_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
