# Generated by Django 4.1.2 on 2022-10-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos_app', '0008_categoria_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'teste',
                'verbose_name_plural': 'testes',
            },
        ),
    ]
