# Generated by Django 4.1.2 on 2022-10-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos_app', '0009_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TESTE',
        ),
    ]
