# Generated by Django 4.1.2 on 2022-10-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0010_delete_historico'),
        ('Produtos_app', '0010_delete_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='publicado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Perfil_app.perfil'),
        ),
    ]
