# Generated by Django 4.1.2 on 2022-10-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos_app', '0012_remove_produto_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem_static_url',
            field=models.CharField(default='img/no_image.png', max_length=128),
        ),
    ]
