# Generated by Django 4.1.2 on 2022-10-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos_app', '0013_categoria_imagem_static_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='informacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
