# Generated by Django 4.1.2 on 2022-10-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Perfil_app', '0010_delete_historico'),
        ('Produtos_app', '0014_produto_informacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('comentado_por', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Perfil_app.perfil')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos_app.produto')),
            ],
        ),
    ]
