# Generated by Django 4.1.2 on 2022-10-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0010_delete_historico'),
        ('Comentarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentado_por',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='Perfil_app.perfil'),
        ),
    ]
