# Generated by Django 4.1.2 on 2022-10-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos_app', '0014_produto_informacao'),
        ('Comentarios_app', '0002_comentario_data_alter_comentario_comentado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Produtos_app.produto'),
        ),
    ]
