# Generated by Django 4.1.2 on 2022-10-16 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produtos_app', '0007_produto_vendido'),
        ('Perfil_app', '0010_delete_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_comprada', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('acao', models.CharField(choices=[('Comprar', 'Comprar'), ('Vender', 'Vender')], max_length=7)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='Perfil_app.perfil')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='Produtos_app.produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='Perfil_app.perfil')),
            ],
            options={
                'verbose_name': 'historico',
                'verbose_name_plural': 'historicos',
            },
        ),
    ]
